### PR TITLE
fix continuous paired undo redo of arbitrary length

### LINKED ISSUE #304: UndoManager sends unexpected XMLNode attribute deletion event during redo()
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
During redo UndoManager sends an XML attribute delete event instead of sending an XML attribute update.

**To Reproduce**
* Create an XML node: ```{"id":"test-node", "a": 100, "b": 0}```
* Update attribute a: ```{"id":"test-node", "a": 200, "b": 0}```
* Update both attributes in a single transaction (**final step**): ```{"id":"test-node", "a": 180, "b": 50}```
* Undo thrice, to remove the node completely from the doc: ```none```
* Redo twice, to get to one step before the final one: ```{"id":"test-node", "a": 200, "b": 0}```
* Redo once again and the result will be: ```{"id":"test-node", "b": 50}```

I created a code to reproduce the issue:
```javascript
import * as Y from "yjs";

const origin = "origin";
const doc = new Y.Doc();
const fragment = doc.getXmlFragment("t");
const undoManager = new Y.UndoManager(fragment, {
  captureTimeout: 0,
  trackedOrigins: new Set([origin]),
});

fragment.observeDeep((events) => {
  events.forEach((evt) => {
    // addition
    evt.changes.added.forEach((item) => {
      item.content.getContent().forEach((cont) => {
        console.log("added: ", cont.nodeName);
      });
    });

    // attribute change
    if (evt.path.length > 0) {
      Array.from(evt.changes.keys.entries()).forEach(([key, change]) => {
        console.log(
          `attrib change. key: '${key}' action: '${change.action}' old: '${
            change.oldValue
          }' new: '${evt.target.getAttribute(key)}'`
        );
      });
    }

    // deleted
    evt.changes.deleted.forEach((item) => {
      item.content.getContent().forEach((cont) => {
        console.log("deleted: ", cont.nodeName);
      });
    });
  });
});

// create element
console.log("============ CREATE ELEMENT ============");
doc.transact(() => {
  const e = new Y.XmlElement("test-node");
  e.setAttribute("a", "100");
  e.setAttribute("b", "0");
  fragment.insert(fragment.length, [e]);
}, origin);

// change one attribute
console.log("============ CHANGE ATTRIBUTE a ============");
doc.transact(() => {
  const e = fragment.get(0);
  e.setAttribute("a", "200");
}, origin);

console.log("============ CHANGE ATTRIBUTE a & b ============");
// change both attributes
doc.transact(() => {
  const e = fragment.get(0);
  e.setAttribute("a", "180");
  e.setAttribute("b", "50");
}, origin);
console.log();

console.log("============ UNDO ============");
undoManager.undo();
console.log("============ UNDO ============");
undoManager.undo();
console.log("============ UNDO ============");
undoManager.undo();

console.log();
console.log("============ REDO ============");
undoManager.redo();
console.log("============ REDO ============");
undoManager.redo();
console.log("============ REDO ============");
undoManager.redo();
```
At the end of this run 'test-node' will be:
```json
{"id:": "test-node", "b": 50}
```

The output of the test code is:
>============ CREATE ELEMENT ============
>added:  test-node
>============ CHANGE ATTRIBUTE a ============
>attrib change. key: 'a' action: 'update' old: '100' new: '200'
>============ CHANGE ATTRIBUTE a & b ============
>attrib change. key: 'a' action: 'update' old: '200' new: '180'
>attrib change. key: 'b' action: 'update' old: '0' new: '50'
>
>============ UNDO ============
>attrib change. key: 'b' action: 'update' old: '50' new: '0'
>attrib change. key: 'a' action: 'update' old: '180' new: '200'
>============ UNDO ============
>attrib change. key: 'a' action: 'update' old: '200' new: '100'
>============ UNDO ============
>deleted:  test-node
>
>============ REDO ============
>added:  test-node
>============ REDO ============
>attrib change. key: 'a' action: 'update' old: '100' new: '200'
>============ REDO ============
>**attrib change. key: 'a' action: 'delete' old: '200' new: 'undefined'**
>attrib change. key: 'b' action: 'update' old: '0' new: '50'

**Expected behavior**
I expect that at the end of running the test code above the 'test-node' to be
```json
{"id": "test-node", "a": 180, "b": 50 }
```

**Screenshots**
N/A

**Environment Information**
 - Browser (Chrome, Firefox, Safari) / Node
 - **Yjs version**: 13.5.6, the issue is there at least since 13.1.0, it might effect earlier versions too

**Additional context**
N/A

### LINKED ISSUE #343: Undo/Redo corrupts nested data 2
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

This is a continuation of https://github.com/yjs/yjs/issues/317

While the example in that issue was solved unfortunately the issue still persists and I made another reproduction here:

https://codesandbox.io/s/hardcore-jang-kkoho?file=/src/index.js

The original issue looked at undoing 2 changes, that was fixed. However 3 or more changes produces the same issue still.

**To Reproduce**

See above

**Expected behavior**

Data not to corrupt

**Environment Information**
 - Yjs version: 13.5.16

### LINKED ISSUE #355: Damaged YMap keys after consecutive redo
**Checklist**

* [x] This is a bug report.
* [x] This report is in the correct repository.

**Describe the bug**
Similar to #343 and #317 but with simpler reproduction path (and arguably more potential impact).

**To Reproduce**
* Add a YMap with at least 2 keys.
* Update 2 of its keys (`x` and `y` in this case, simulate element dragging in real world apps) for 3 or more times.
* Undo until the YMap is deleted.
* Redo to latest state, these 2 keys are lost.

See [code sandbox](https://codesandbox.io/s/little-waterfall-q9fx5?file=/src/index.js) or following snippet:

``` js
const doc = new Y.Doc();
const yRoot = doc.getMap();
const undoMgr = new Y.UndoManager(yRoot);

const yPoint = new Y.Map();
yPoint.set("x", 0);
yPoint.set("y", 0);
yRoot.set("a", yPoint);
undoMgr.stopCapturing();

yPoint.set("x", 100);
yPoint.set("y", 100);
undoMgr.stopCapturing();

yPoint.set("x", 200);
yPoint.set("y", 200);
undoMgr.stopCapturing();

yPoint.set("x", 300);
yPoint.set("y", 300);
undoMgr.stopCapturing();

undoMgr.undo(); // x=200, y=200
undoMgr.undo(); // x=100, y=100
undoMgr.undo(); // x=0, y=0
undoMgr.undo(); // nil

undoMgr.redo(); // x=0, y=0
undoMgr.redo(); // x=100, y=100
undoMgr.redo(); // x=200, y=200
undoMgr.redo(); // expected x=300, y=300, actually nil

console.log(yRoot.toJSON());
```

**Expected behavior**
As listed in the snippet, the affected map keys shouldn't be missing.

This can be a blocker for using Yjs as "single source of truth" model layer. And although there can be some way patching the state of view layers (say DOM elements), if we use Yjs instances for serializing data to DB on Node.js, in this case user may found the elements they updated were missing :(

**Environment Information**
- Browser and Node.js, with lastest version of Yjs.

**Additional context**
The bug only happens after the paired `yMap.set` updates for 3 times or more. I can confirm that when such update happens for 2 times or less, we got similar bug until the fix in #317.

I also did some quick search in the codebase and here are something I noticed:

* Using `deleteFilter: () => false` config in UndoManager can be an overkill workaround, since it prevents the element from being deleted when undoing.
* Inspecting `doc.store.clients.get(doc.clientID)` shows the item sequence and some correlation can be found. Say for the first `Item` representing the first YMap insertion, its `redone` links exactly to the last undo that caused the problem. But the data structure still looks obscure, for the expected redo result, are there some constraints that the data structure should follow?
* There was a `@todo` comment in `followRedone` ([link](https://github.com/yjs/yjs/commit/aeb23dbaa9effbd848601dd9ba4b1526ce35088b#diff-8e03df4677fec8fdd3103498dd8f3114030b2d18bca59ac692a122795103ab82R38)) in the previous bug fix, is it related to this issue?

We use Yjs in our collaborative app and it generally works awesome, I am willing to provide help within my capacity, thanks.

### PR DESCRIPTION
**Pull request by doodlewind**
Fix #355 
Fix #343 
Fix #304

Merry Christmas!

### CODE REVIEW

**Comment by nc** [comment]
Just tried this in our app and it fixes the above issues, thanks!

**Comment by doodlewind** [comment]
This is the case analysis for #355.

For the following problematic code in that issue, there are 9 items before undo:

``` js
yRoot.set('a', yElement) //  item 0
yElement.set('left', 0) // item 1
yElement.set('top', 0) // item 2

undoMgr.stopCapturing()
yElement.set('left', 100) // item 3
yElement.set('top', 100) // item 4

undoMgr.stopCapturing()
yElement.set('left', 200) // item 5
yElement.set('top', 200) // item 6

undoMgr.stopCapturing()
yElement.set('left', 300) // item 7
yElement.set('top', 300) // item 8
```

After 4 consecutive undo and 4 consecutive redo, the items will change as follows:

``` js
// toRedo [5, 6], toDelete [7, 8]
// new inserted items [9, 10]
undoMgr.undo() // 200, 200

// toRedo [3, 4], toDelete [9, 10]
// new inserted items [11, 12]
undoMgr.undo() // 100, 100

// toRedo [1, 2], toDelete [11, 12]
// new inserted items [13, 14]
undoMgr.undo() // 0, 0

// toRedo [], toDelete [0, 13, 14]
// no inserted items
undoMgr.undo() // {} all items 0-14 are deleted now

// toRedo [0, 13, 14], toDelete []
// new inserted items [15, 16, 17]
// items 15 has origin 0
undoMgr.redo() // 0, 0

// toRedo [11, 12], toDelete [16, 17]
// new inserted items [18, 19]
undoMgr.redo() // 100, 100

// toRedo [9, 10], toDelete [18, 19]
// new inserted items [20, 21]
undoMgr.redo() // 200, 200

// toRedo [7, 8], toDelete [20, 21]
// new inserted items [22, 23] but both are deleted
undoMgr.redo() // should be 300, 300
```

However, if there are 3 consecutive undo and 3 consecutive redo, the correct flow of items would look like this:

``` js
// toRedo [3, 4], toDelete [5, 6]
// new inserted items [7, 8]
undoMgr.undo() // 100, 100

// toRedo [1, 2], toDelete [7, 8]
// new inserted items [9, 10]
undoMgr.undo() // 0, 0

// toRedo [], toDelete [0, 9, 10]
// no inserted items
undoMgr.undo() // {}

// toRedo [0, 9, 10], toDelete []
// new inserted items [11, 12, 13]
// item 11 has origin 0
undoMgr.redo() // 0, 0

// toRedo [7, 8], toDelete [12, 13]
// new inserted items [14, 15]
undoMgr.redo() // 100, 100

// toRedo [5, 6], toDelete [14, 15]
// new inserted items [16, 17]
undoMgr.redo() // 200, 200
```

In the 3-time-undo case, the `left` of item 16  is 14, which is the item inserted on the penultimate redo. Based on this mapping, in the 4-time-undo case, the `left` of item 22 should be 20, but it's actually 16. The reason for this problem is that in the previous `redoItem` [fix](https://github.com/yjs/yjs/commit/995fbfa4cc7692bf18f3fd37c8faeff729de7c0f), we would try to move right to get the item in `itemsToDelete`. But in the 4-time-undo case, we need to move right furthermore in order to find the item in `itemsToDelete`. Based on this analysis, we can get the fix as what this PR raised.

@dmonad could you please take a look? Thanks.

**Comment by kirill-konshin** [comment]
Any chance to have this merged soon?

**Comment by dmonad** [comment]
Thank you for this @doodlewind! I imagine it took quite some time to delve into this. Thank you in particular for the tests case in the other issue. It really helped.

The problem was a bit more complicated and I fear your changes would have broken other things. Today I had a clear mind to work this out. I reworked the UndoManager and fixed all known issues (I hope). I also added more tests to this repository.

This is my fix: https://github.com/yjs/yjs/compare/v13.5.24...v13.5.25

I just published a new release based on the changes: Yjs@v13.5.25

**Pull request closed without merging**
