### PR TITLE
:bug: fix for #187

### PR DESCRIPTION
**Pull request by ISNIT0**
Fix for https://github.com/yjs/yjs/issues/187

I feel like this whole area deserves a re-write. Lots of duplication now and it's not obvious what the flow is (`packStr` seems pretty smelly to me)

### CODE REVIEW

**Comment by ISNIT0** [comment]
@dmonad 👋 Would be great to get this reviewed soon

**Comment by ISNIT0** [comment]
🙏

**Comment by dmonad** [comment]
Thanks for the PR!  If you are interested you are welcome to refactor generating the deltas :-) 

I'll publish a new release in a bit. I first have to keep up with some breaking typescript changes..

**Comment by dmonad** [comment]
>  yjs 13.0.5 published 🎉

**Comment by dmonad** [comment]
I'll also publish a new y-quill release with updated dependencies.

**Comment by ISNIT0** [comment]
Wahoo! Thanks so much @dmonad Love quick releases 👍

**Pull request merged**
